[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "javascript"
language-servers = [ "biome", { name = "typescript-language-server", except-features = [ "format" ] } ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "biome", { name = "typescript-language-server", except-features = [ "format" ] } ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ "biome", { name = "typescript-language-server", except-features = [ "format" ] } ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome"]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
